# Generated by Django 6.0.5 on 2026-05-31 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyurtma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mijoz_ism', models.CharField(max_length=200)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('holat', models.CharField(choices=[('yangi', 'Yangi'), ('jarayonda', 'Jarayonda'), ('bajarildi', 'Bajarildi'), ('bekor', 'Bekor qilindi')], default='yangi', max_length=20)),
                ('izoh', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('miqdor', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('birlik', models.CharField(default='dona', max_length=20)),
                ('minimal_miqdor', models.DecimalField(decimal_places=2, default=5, max_digits=10)),
                ('narx', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='MoliyaviyYozuv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('daromad', 'Daromad'), ('xarajat', 'Xarajat')], max_length=20)),
                ('summa', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField(auto_now_add=True)),
                ('tavsif', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name': 'Moliyaviy yozuv',
                'verbose_name_plural': 'Moliyaviy yozuvlar',
                'ordering': ['-sana'],
            },
        ),
        migrations.CreateModel(
            name='Xodim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('lavozim', models.CharField(choices=[('barista', 'Barista'), ('ofitsiant', 'Ofitsiant'), ('oshpaz', 'Oshpaz'), ('menejer', 'Menejer'), ('kassir', 'Kassir')], max_length=20)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('maosh', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ishga_kirgan', models.DateField(auto_now_add=True)),
                ('faolmi', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
                'ordering': ['familiya', 'ism'],
            },
        ),
        migrations.CreateModel(
            name='BuyurtmaQatori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mahsulot_nomi', models.CharField(max_length=200)),
                ('miqdor', models.PositiveIntegerField(default=1)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=10)),
                ('buyurtma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qatorlar', to='erp.buyurtma')),
            ],
        ),
    ]
