# Generated by Django 6.0.5 on 2026-06-08 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xodim',
            name='lavozim',
            field=models.CharField(choices=[('ombor_mudiri', 'Ombor mudiri'), ('omborchi', 'Omborchi'), ('savdo_vakili', 'Savdo vakili'), ('logist', 'Logist'), ('buxgalter', 'Buxgalter'), ('haydovchi', 'Haydovchi')], max_length=20),
        ),
    ]
