# Generated by Django 6.0.5 on 2026-05-31 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mijoz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=100)),
                ('familiya', models.CharField(max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('tugilgan_kun', models.DateField(blank=True, null=True)),
                ('manzil', models.TextField(blank=True)),
                ('izoh', models.TextField(blank=True)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mijoz',
                'verbose_name_plural': 'Mijozlar',
                'ordering': ['-qoshilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Muloqot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(choices=[('tashrif', 'Tashrif'), ('qongiroq', "Qo'ng'iroq"), ('email', 'Email'), ('izoh', 'Izoh')], default='izoh', max_length=20)),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('izoh', models.TextField()),
                ('mijoz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muloqotlar', to='crm.mijoz')),
            ],
            options={
                'verbose_name': 'Muloqot',
                'verbose_name_plural': 'Muloqotlar',
                'ordering': ['-sana'],
            },
        ),
    ]
